baseURL = "/"
title = "inb4doc"
theme = "book"
contentDir = "../content"
disableKinds = ["RSS", "sitemap"]

[security]
  [security.funcs]
    getenv = ["^EDITOR_URL$", "^HUGO_", "^CI$"]

[params]
  BookSearch = true
  BookTheme = "auto"
  BookSection = "docs"
  description = "Live markdown editor for browser, desktop, and mobile. Connect providers to export wikis, static sites, and more."
