baseURL = "/"
title = "inb4doc"
theme = "book"
contentDir = "../content"
disableKinds = ["RSS", "sitemap"]

[security]
  [security.funcs]
    getenv = ["^EDITOR_URL$", "^HUGO_", "^CI$"]

[params]
  BookSearch = true
  BookTheme = "auto"
  BookSection = "docs"
  description = "Edit markdown in a live WYSIWYG editor across browser, desktop, and mobile. Connect multiple providers to export wikis, static sites, or other formats."
