main = "docker"

[[stages]]
name = "build-install"
description = "Install local bun dependencies"
type = "binary"
binary = "bun"
args = ["install"]

[[stages]]
name = "build"
description = "Build editor static assets"
type = "binary"
binary = "bun"
depends = ["build-install"]
outputs = ["root://public/"]
args = ["run", "build"]

[[stages]]
name = "docker"
description = "Build editor static assets via Docker"
type = "docker"
outputs = ["root://public/"]
recipe = "images/web.Dockerfile"
target = "/output/editor/public/"
dest = "root://public/"

[[stages]]
name = "docker-desktop"
description = "Build editor static assets via Docker"
type = "docker"
outputs = ["root://public/"]
recipe = "images/desktop.Dockerfile"
target = "/output/editor/public/"
dest = "root://public/"

[[stages]]
name = "android"
description = "Build Android APK via Docker"
type = "docker"
outputs = ["root://android/bin/inb4doc.apk"]
recipe = "images/android.Dockerfile"
target = "/output/apk/app-debug.apk"
dest = "root://android/bin/inb4doc.apk"
